server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbs?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.util.DriverDataSource
#    hikari:
#      minimum-idle: 20
#      maximum-pool-size: 100
#      auto-commit: true
#      idle-timeout: 5000
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: select 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


